// frontend/src/components/models/VariantDialog.vue
<template>
  <div class="variant-dialog-overlay fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50" @click="$emit('close')">
    <div class="variant-dialog bg-white dark:bg-gray-800 rounded-lg shadow-2xl p-6 max-w-2xl w-full mx-4" @click.stop>
      <div class="header mb-4">
        <h2 class="text-2xl font-bold mb-2">Select Model Variant</h2>
        <p class="text-sm text-gray-600 dark:text-gray-400">Choose a quantization for {{ modelKey }}</p>
      </div>

      <div class="variants-list space-y-3">
        <div
          v-for="variant in variants"
          :key="variant.quantization"
          class="variant-item p-4 border-2 border-gray-200 dark:border-gray-700 rounded-lg hover:border-blue-500 cursor-pointer transition-colors"
          @click="$emit('select', variant)"
        >
          <div class="flex items-center justify-between">
            <div>
              <div class="font-semibold text-lg">{{ variant.quantization }}</div>
              <div class="text-sm text-gray-600 dark:text-gray-400">{{ variant.name }}</div>
            </div>
            <div class="text-right">
              <div class="text-sm font-semibold text-blue-600">{{ variant.size_estimate }}</div>
              <div class="text-xs text-gray-500">{{ getQualityLabel(variant.quantization) }}</div>
            </div>
          </div>
        </div>
      </div>

      <div class="actions mt-6 flex justify-end">
        <button
          @click="$emit('close')"
          class="px-4 py-2 bg-gray-200 dark:bg-gray-700 text-gray-800 dark:text-gray-200 rounded-lg hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors"
        >
          Cancel
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
defineProps<{
  modelKey: string
  variants: any[]
}>()

const emit = defineEmits(['select', 'close'])

const getQualityLabel = (quant: string) => {
  const labels: Record<string, string> = {
    'Q4_K_M': 'Balanced',
    'Q4_K_S': 'Fast & Small',
    'Q5_K_M': 'High Quality',
    'Q6_K': 'Very High Quality',
    'Q8_0': 'Maximum Quality'
  }
  return labels[quant] || 'Custom'
}
</script>

// frontend/src/components/models/VariantDialog.tsx
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { X } from 'lucide-react'

interface VariantDialogProps {
  modelKey: string
  variants: any[]
  onSelect: (variant: any) => void
  onClose: () => void
}

export const VariantDialog = ({ modelKey, variants, onSelect, onClose }: VariantDialogProps) => {
  const getQualityLabel = (quant: string) => {
    const labels: Record<string, string> = {
      'Q4_K_M': 'Ausgewogen',
      'Q4_K_S': 'Schnell & Klein',
      'Q5_K_M': 'Hohe Qualität',
      'Q6_K': 'Sehr hohe Qualität',
      'Q8_0': 'Maximale Qualität'
    }
    return labels[quant] || 'Benutzerdefiniert'
  }

  return (
    <div
      className="fixed inset-0 bg-black/50 flex items-center justify-center z-50"
      onClick={onClose}
    >
      <Card
        className="p-6 max-w-2xl w-full mx-4 max-h-[80vh] overflow-y-auto"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-start justify-between mb-4">
          <div>
            <h2 className="text-2xl font-bold mb-2">Modellvariante auswählen</h2>
            <p className="text-sm text-muted-foreground">
              Wähle eine Quantisierung für {modelKey}
            </p>
          </div>
          <Button variant="ghost" size="icon" onClick={onClose}>
            <X className="w-4 h-4" />
          </Button>
        </div>

        <div className="space-y-3">
          {variants.map((variant) => (
            <div
              key={variant.quantization}
              className="p-4 border-2 rounded-lg hover:border-primary cursor-pointer transition-colors"
              onClick={() => onSelect(variant)}
            >
              <div className="flex items-center justify-between">
                <div>
                  <div className="font-semibold text-lg">{variant.quantization}</div>
                  <div className="text-sm text-muted-foreground">{variant.name}</div>
                </div>
                <div className="text-right">
                  <div className="text-sm font-semibold text-primary">
                    {variant.size_estimate}
                  </div>
                  <Badge variant="secondary" className="text-xs">
                    {getQualityLabel(variant.quantization)}
                  </Badge>
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-6 flex justify-end">
          <Button variant="secondary" onClick={onClose}>
            Abbrechen
          </Button>
        </div>
      </Card>
    </div>
  )
}
